### ISSUE TITLE
IMAGES: Some images seem not to be rendered correct

### ISSUE THREAD

**Issue by Nostritius** [xoreos/phaethon#31]
![bildschirmfoto vom 2018-07-08 14-56-54](https://user-images.githubusercontent.com/17826813/42419999-6a0a81ec-82bf-11e8-8dd5-3f61dc1ce7a5.png)
I experienced that some images from kotor (the portraits)
 seem not to be rendered correcty.

**Comment by DrMcCoy** [comment]
0.0.4+401? Can you update your repository? I think that's a bug I already fixed

**Comment by DrMcCoy** [comment]
Specifically, 204ae31ca786ea9594af7c189989caa7caa33c39 should fix this, which is 0.0.4+404.g204ae31

**Comment by Nostritius** [comment]
Ah, my mistake, the new version fixed this.
