### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by rjshae** [xoreos/phaethon#38]
On a Windows system I have MSYS2 installed with Mingw-w64, as per the wiki
information about compiling xoreos-tools. While building this package, I
received the following message:

$ ./autogen.sh && ./configure && make
...
checking for Qt5Core >= 5.7.1 Qt5Gui >= 5.7.1 Qt5Widgets >= 5.7.1 Qt5Concurrent >= 5.7.1... no
configure: error: Qt5 (>= 5.7.1, modules Core, Gui, Widgets, Concurrent) is required and could not be found!

This was resolved as follows:

$ pacman -S mingw-w64-x86_64-qt-creator

**Comment by DrMcCoy** [comment]
Thanks, added a page on our wiki on how to compile Phaethon, including your fix: https://wiki.xoreos.org/index.php?title=Compiling_Phaethon :)
