### ISSUE TITLE
Does not build on Fedora 26

### ISSUE THREAD

**Issue by RiderExMachina** [xoreos/phaethon#6]
The build is unable to find wxWidgets; which one is needed?

**Comment by DrMcCoy** [comment]
Currently, Phaethon needs wxWidgets >= 3.0.0. Be sure to also install the dev packages. On Fedora, I think the relevant package are wxGTK3 and wxGTK3-devel.

**Comment by RiderExMachina** [comment]
>wxGTK3 and wxGTK3-devel

That was it! How would one contribute this (or something like this) to the Wiki?
